@url = http://localhost:4400
@url2 = https://starfish-app-m7u82.ondigitalocean.app


GET http://localhost:4400

### 

GET http://localhost:4400/womens

###

GET http://localhost:4400/womens/2

###

POST http://localhost:4400/login
Content-Type: application/json

{
    "email": "lisa.millerd@gmail.com",
    "password": "1234"
}

###
GET {{url2}}/admin-view

###

POST {{url2}}/admin-add
Content-Type: application/json

    {
    "image": "test from server",
    "image2": "test",
    "image3": "string",
    "image4": "string",
    "image5": "string",
    "title": "string", 
    "description": "string",
    "price": 22,
    "stock": 0
    }

###
GET {{url}}/admin-edit/2

###
PUT {{url}}/admin-update/26
Content-Type: application/json

{
    "image": "update from server",
    "image2": "test",
    "image3": "string",
    "image4": "string",
    "image5": "string",
    "title": "string", 
    "description": "string",
    "price": 22,
    "stock": 0
}
###

PUT {{url2}}/admin-revert/28
Content-Type: application/json

{
    "title": "revert test2", 
    "description": "revert test",
    "price": 22,
    "stock": 0
}

###
DELETE {{url}}/admin-delete/20

###
PUT {{url}}/admin-toggle/26
